### ISSUE TITLE
varnothing used by LaTeX

### ISSUE THREAD

**Issue by Myriad-Dreamin** [johanvx/typst-undergradmath#10]
The `\varnothing` used by LaTeX is not essentially a "nothing", which is stolen from the symbol "diameter", e.g. `⌀10cm`.

Try it:
```typst
#let varnothing = $\u{2300}$
```

See also [unimath](https://texdoc.org/serve/unimath-symbols.pdf/0) and search `U+02300` or `\diameter`

**Comment by johanvx** [comment]
While it's semantically bad, I'll use the Typst symbol `diameter` in the document for the `\varnothing` in LaTeX. Thanks for letting me know the `\varnothing` thing!

## My observations
If copy the characters in Line `U+02205` of [newcm-unimath-symbols] and paste them in [Compart/Unicode], it can be easily found that they're all [Empty Set `U+2205`]. The characters in Line `U+02300` are [Diameter Sign `U+2300`]. **Both are reasonable.** 

![varnothing](https://user-images.githubusercontent.com/61529310/230595567-b7b88a7b-60b4-414a-ab2b-6f17eb8771f0.png)

![diameter](https://user-images.githubusercontent.com/61529310/230601642-19c57194-0acf-4f29-94eb-6a24dcaac45e.png)

In Subsection 13.3 of [newcm-doc](https://mirrors.sustech.edu.cn/CTAN/fonts/newcomputermodern/doc/newcm-doc.pdf), however, the `\varnothing` character $\varnothing$ is Diameter Sign `U+2300`. **This is a case of stealing the symbol `\diameter`.**

![Subsection 13.3 of newcm-doc](https://user-images.githubusercontent.com/61529310/230601832-0780f8a8-ee7c-4bc5-b779-f976310a58e9.png)

[newcm-unimath-symbols]: https://mirrors.sjtug.sjtu.edu.cn/ctan/fonts/newcomputermodern/doc/newcm-unimath-symbols.pdf
[Compart/Unicode]: https://www.compart.com/en/unicode/
[Empty Set `U+2205`]: https://www.compart.com/en/unicode/U+2205
[Diameter Sign `U+2300`]: https://www.compart.com/en/unicode/U+2300

**Comment by Myriad-Dreamin** [comment]
By your comment, I found that some fonts tried to make the shape of `nothing` look like `diameter`. It brings a good news that the builtin font "Fira Sans" can help us define the `varnothing` with correct semantics, and without using unicode.

```typst
#let varnothing = $text(font: "Fira Sans", nothing)$
```

I compared 3 different approaches to defining `varnothing`. Though, I still prefer the diameter symbol.

```typst
#let big = $text(font: "Fira Sans", nothing)$
#let regular = $diameter$
#let small = $text(font: "Fira Sans", diameter)$
```

**Comment by johanvx** [comment]
Sorry for the late reply. Would you mind creating a PR into `main` for this issue? The PR may need to:

- Use `diameter` in Typst for `\varnothing` in LaTeX. (I personally don't think this is a `@tricky`, but it's a **you-decide**.)
- Rewrite the `/ Remark:`. (Would it be useful to add a link to this issue?)

Feel free to modify anything as long as necessary.
