### ISSUE TITLE
Incorrect link reference

### ISSUE THREAD

**Issue by Myriad-Dreamin** [johanvx/typst-undergradmath#25]
I found the link points to a 404 page during testing :).

https://github.com/johanvx/typst-undergradmath/blob/7832fd3a35d2d4f88a974eb441235ba71d3aa62e/undergradmath.typ#L398-L399

Perhaps it should be https://typst.app/docs/reference/types/array/

**Comment by johanvx** [comment]
Yes! I didn't notice that. Thanks for pointing it out!
