### ISSUE TITLE
Simpler approach to get `\varnothing` in LaTeX (slashed circle empty set)

### ISSUE THREAD

**Issue by CarrotDLaw** [johanvx/typst-undergradmath#40]
In the latest version of Typst, the following code can correctly output `nothing` in slashed circle shaped without any semantic ambiguities using the default New Computer Modern Math font. Alternative fonts or using `diameter` as `nothing` is no longer needed. [More reference here.](https://sitandr.github.io/typst-examples-book/book/basics/math/symbols.html?highlight=nothing#empty-set)

```typst
#show math.equation: text.with(features: ("cv01",))

$
nothing quad &"nothing" &"U+2205" \
diameter quad &"diameter" &"U+2300"
$
```

<img width="555" alt="image" src="https://github.com/johanvx/typst-undergradmath/assets/52628857/0eb49520-54c2-4e73-8295-1a680b05f087">

The documentation of New Computer Modern font has been updated so the referenced section number might need to be updated as well.

**Comment by johanvx** [comment]
Thanks! I'll update the document in the near future.

**Comment by johanvx** [comment]
I couldn't find a good way to express it while keeping 2-page layout, so I decided to 'invite' readers to read Typst Examples Book 😝 .

**Comment by CarrotDLaw** [comment]
> In the latest version of Typst, the following code can correctly output `nothing` in slashed circle shaped without any semantic ambiguities using the default New Computer Modern Math font. Alternative fonts or using `diameter` as `nothing` is no longer needed. [More reference here.](https://sitandr.github.io/typst-examples-book/book/basics/math/symbols.html?highlight=nothing#empty-set)
> 
> ```typst
> #show math.equation: text.with(features: ("cv01",))
> 
> $
> nothing quad &"nothing" &"U+2205" \
> diameter quad &"diameter" &"U+2300"
> $
> ```
> 
> <img alt="image" width="555" src="https://private-user-images.githubusercontent.com/52628857/329972614-0eb49520-54c2-4e73-8295-1a680b05f087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjMyMTUsIm5iZiI6MTcxNTY2MjkxNSwicGF0aCI6Ii81MjYyODg1Ny8zMjk5NzI2MTQtMGViNDk1MjAtNTRjMi00ZTczLTgyOTUtMWE2ODBiMDVmMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA1MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMjE2N2NjNjUwOTFiZGU4MjIyMTc0NDY2NDM2MTFkODljNWU2NzQxNWZhYjMzNmRlNTQyMDEzNGVmNTA5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NEBTyw0ra5ShER6jFUN2anzRdzssVwZYtsPQuwQMPmc">
> 
> The documentation of New Computer Modern font has been updated so the referenced section number might need to be updated as well.

Would the updated one be a bit misleading? When using `CV01`, `nothing` is NOT `diameter` U+2300. It can be correctly shown as U+2205, in slashed circle shape. The updated solution (`let varnothing = math.diamter`) will make`varnothing` to be U+2300. The best solution should be simply enabling on `CV01` for New Computer Modern font in Typst.

**Comment by johanvx** [comment]
> Would the updated one be a bit misleading? When using `CV01`, `nothing` is NOT `diameter` U+2300. `nothing` CAN be correctly shown as U+2205 in slashed circle shape. The updated solution (`let varnothing = math.diamter`) will make`varnothing` to be U+2300, which is wrong in semantic. The best solution should be simply enabling on `CV01` for New Computer Modern font in Typst.

I'm not so sure, but let's do a quick check:

1. copy-paste your code and add a Fira Math version duplication (https://typst.app/project/rZiKl-oIw0jTMEb5IAJ1p5) and download the compiled PDF.

   ```typst
   #set page(width: auto, height: auto, margin: 1em)

   #show math.equation: text.with(features: ("cv01",))

   $
     nothing quad &"nothing" &"U+2205" \
     diameter quad &"diameter" &"U+2300"
   $

   #show math.equation: text.with(font: "Fira Math")

   $
     nothing quad &"nothing" &"U+2205" \
     diameter quad &"diameter" &"U+2300"
   $
   ```

2. copy the two New Computer Modern Math symbols and paste them one by one to https://www.compart.com/en/unicode. It turns out that the two symbols are all `“⌀” U+2300 Diameter Sign Unicode Character`.

3. do the same check with the two Fira Math symbols. It turns out that the first symbol is `“∅” U+2205 Empty Set Unicode Character` and the second `“⌀” U+2300 Diameter Sign Unicode Character`.

**Comment by CarrotDLaw** [comment]
I have tried and you are right!! The reason my code works as expected is that I have been using the (Typst Preview Extension)[https://github.com/Enter-tainer/typst-preview] to check the output. It is correctly `nothing` on the preview output, but not the final PDF output. Now I'm not sure whose fault it is.

**Comment by CarrotDLaw** [comment]
Guiding readers to read the possible solutions and let them choose their own way is good enough.
