### ISSUE TITLE
doteq used by LaTeX

### ISSUE THREAD

**Issue by Myriad-Dreamin** [johanvx/typst-undergradmath#9]
According to [symbl](https://symbl.cc/en/2250/), a good symbol `≐` introduced by unicode early is U+2250, which named "Approaches the Limit".

> Symbol Meaning
> Approaches the Limit. Mathematical Operators.
> 
> Approaches the Limit was approved as part of Unicode 1.1 in 1993.

So you can try:
```typst
// <module dotx>
#let eq = $\u{2250}$
```

According to [unimath](https://texdoc.org/serve/unimath-symbols.pdf/0), they also use U+2250 as `\doteq`

**Comment by johanvx** [comment]
Oh, I didn't know this. Thanks for pointing it out!

**Comment by johanvx** [comment]
@Myriad-Dreamin would you mind leaving me an email (such as a GitHub-provided `no-reply` email) for [creating co-authored commits](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)?
